import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import initTranslations from "../i18n";
import { FC, PropsWithChildren } from "react";
import Footer from "@/components/Footer";
import { i18nNamespaces } from "../_lib/common";
import TranslationsProvider from "@/components/TranslationsProvider";
import Head from "next/head";

const sora = Sora({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "AyEstate",
  description: "Generated by create next app",
};

type TRootLayout = PropsWithChildren & {
  params: {
    locale: string;
  };
};
const RootLayout: FC<TRootLayout> = async ({
  params: { locale },
  children,
}) => {
  const { t, resources } = await initTranslations(locale, i18nNamespaces);

  return (
    <html lang="en">
      <Head>
        <meta name="robots" content="noindex" />
        <meta name="Googlebot" content="noindex" />
      </Head>

      <body className={`${sora.className}`}>
        <TranslationsProvider
          namespaces={i18nNamespaces}
          locale={locale}
          resources={resources}
        >
          <Navbar />
          <main>{children}</main>
          <Footer t={t} />
        </TranslationsProvider>
      </body>
    </html>
  );
};

export default RootLayout;
